export const nodeLibraryCategories = [
  {
    title: '数据源',
    icon: '[SRC]',
    accent: '#22c55e',
    defaultOpen: true,
    items: [
      {
        type: 'excel-upload',
        label: 'Excel读取',
        description: '读取Excel文件',
        icon: '[XLS]',
        accent: '#22c55e',
      },
      {
        type: 'csv-read',
        label: 'CSV读取',
        description: '读取CSV/TSV文件',
        icon: '[CSV]',
        accent: '#22c55e',
      },
    ],
  },
  {
    title: '数据清洗',
    icon: '[CLN]',
    accent: '#3b82f6',
    defaultOpen: true,
    items: [
      {
        type: 'data-clean',
        label: '数据清洗',
        description: '筛选/计算/重命名',
        icon: '[FLTR]',
        accent: '#2563eb',
      },
      {
        type: 'type-convert',
        label: '类型转换',
        description: '转换列数据类型',
        icon: '[TYP]',
        accent: '#2563eb',
      },
      {
        type: 'missing-handle',
        label: '缺失值处理',
        description: '处理空值/NA',
        icon: '[NA]',
        accent: '#38bdf8',
      },
      {
        type: 'deduplicate',
        label: '去重',
        description: '删除重复行',
        icon: '[DEDUP]',
        accent: '#38bdf8',
      },
      {
        type: 'text-process',
        label: '文本处理',
        description: '文本清洗与转换',
        icon: '[Str.]',
        accent: '#38bdf8',
      },
      {
        type: 'date-process',
        label: '日期处理',
        description: '日期提取与计算',
        icon: '[DATE]',
        accent: '#14b8a6',
      },
    ],
  },
  {
    title: '数据分析',
    icon: '[ANL]',
    accent: '#f59e0b',
    defaultOpen: false,
    items: [
      {
        type: 'group-aggregate',
        label: '分组聚合',
        description: '类似SQL GROUP BY',
        icon: '[GRP]',
        accent: '#f59e0b',
      },
      {
        type: 'pivot-table',
        label: '透视表',
        description: '创建数据透视表',
        icon: '[PIV]',
        accent: '#f59e0b',
      },
      {
        type: 'unpivot',
        label: '逆透视',
        description: '宽表转长表',
        icon: '[UNP]',
        accent: '#fbbf24',
      },
    ],
  },
  {
    title: '多表操作',
    icon: '[JOIN]',
    accent: '#6366f1',
    defaultOpen: false,
    items: [
      {
        type: 'multi-join',
        label: '多表关联',
        description: '类似SQL Join',
        icon: '[JOIN]',
        accent: '#6366f1',
      },
      {
        type: 'vertical-merge',
        label: '纵向合并',
        description: '多表上下拼接',
        icon: '[MERGE]',
        accent: '#a855f7',
      },
      {
        type: 'vlookup',
        label: 'VLOOKUP',
        description: '类似Excel查找',
        icon: '[V]',
        accent: '#a855f7',
      },
      {
        type: 'table-diff',
        label: '表格对比',
        description: '比较两表差异',
        icon: '[DIFF]',
        accent: '#a855f7',
      },
      {
        type: 'reconcile',
        label: '对账核算',
        description: '自动汇总对比核算',
        icon: '[CHK]',
        accent: '#e11d48',
      },
    ],
  },
  {
    title: 'AI/自动化',
    icon: '[AI]',
    accent: '#ef4444',
    defaultOpen: false,
    items: [
      {
        type: 'ai-process',
        label: 'AI智能处理',
        description: '大模型批量处理',
        icon: '[AI]',
        accent: '#ef4444',
      },
      {
        type: 'python-script',
        label: 'Python脚本',
        description: '自定义Python代码',
        icon: '[PY]',
        accent: '#f97316',
      },
    ],
  },
  {
    title: '输出',
    icon: '[OUT]',
    accent: '#64748b',
    defaultOpen: false,
    items: [
      {
        type: 'export-excel',
        label: '导出Excel',
        description: '保存结果文件',
        icon: '[XLS]',
        accent: '#94a3b8',
      },
      {
        type: 'export-csv',
        label: '导出CSV',
        description: '保存为CSV',
        icon: '[CSV]',
        accent: '#94a3b8',
      },
    ],
  },
];

export default nodeLibraryCategories;
